ndcfg_tau: 0
dilate_tau: 0
inflate_tau: 0
sdedit_tau: 0
dilate_settings: ~
inflate_settings: ~
ndcfg_dilate_settings: ~
inflate_transform: ~
progressive: false
num_inference_steps: 50
inference_batch_size: 1
num_iters_per_prompt: 1
latent_height: 256
latent_width: 256
pixel_height: 2048
pixel_width: 2048
